version: "3.3"
services:
  fhir-server:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    configs:
      - source: hapi
        target: /data/hapi/lucenefiles/application.yaml
    ports:
      - "8080:8080"
    volumes:
      - "./src:/tmp/hapi-fhir-jpaserver-starter/src/"
    environment:
      SPRING_CONFIG_LOCATION: '/data/hapi/lucenefiles/application.yaml'
  fhir-server-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_DB:${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes: 
      - "data:/var/lib/postgresql/data"
  fhir-patient-generator:
    image: siddkhewal/synthea:0.1
    ports:
      - "8000:80"
    volumes:
      - "synthea:/synthea"
volumes:
  data:
  synthea:
configs:
  hapi:
    file: ./application.yaml
