version: "3.3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    configs:
      - source: hapi
        target: /data/hapi/lucenefiles/application.yaml
    ports:
      - "8080:8080"
    volumes:
      - "./src:/tmp/hapi-fhir-jpaserver-starter/src/"
    environment:
      SPRING_CONFIG_LOCATION: '/data/hapi/lucenefiles/application.yaml'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      POSTGRES_DB: fhirdb
    ports:
      - "5432:5432"
    volumes: 
      - "data:/var/lib/postgresql/data"
  synthea:
    image: smartonfhir/synthea
    ports:
      - "8000:80"
    volumes:
      - "synthea:/synthea"
volumes:
  data:
  synthea:
configs:
  hapi:
    file: ./application.yaml
